Greetings! For the test assignment I chose YY1 TF data from Homo sapiens sample GM12892. See link https://www.encodeproject.org/experiments/ENCSR000BLT/ for more details.

In this notebook you will find how to select top 1000 peaks based on qValue. Why choose qValue? 1.ENCODE preocessed and released data have pValue column unassigned and filled with -1, so we are unable to choose top peaks. In the test assignment pValue was the quality metrics for selection, but column values are useless(thanks to ENCODE and/or researchers who released data this way). 2.On the other hand, qValue column filled properly. It is measurement of statistical significance using false discovery rate (-log10). To put in simple, the more is qValue in result file (narrowPeak .bed), the more significant peaks are. See http://genome.ucsc.edu/FAQ/FAQformat.html#format12 for more details.
Citing from here:https://www.biorxiv.org/content/biorxiv/suppl/2017/04/10/120113.DC2/120113-1.pdf
A peak call with a larger signal value has a smaller p- and q-value, which indicates that it is more likely to reflect an actual protein-DNA binding event. Thus, a larger signal value will translate to a larger − log10(p-value) and − log10(q-value).

In [1]:
import numpy as np
import pandas as pd

In [17]:
bed_Np_headers = ['chrom','chromStart','chromEnd','name','score','strand','signalValue','pValue','qValue','peak']

In [19]:
bed_Np_orig = pd.read_csv('/home/ignat/Downloads/chip_seq_test/unpack/ENCFF329MHR_12892.bed',sep = '\t',names = bed_Np_headers)

In [20]:
bed_Np_orig

,chrom,chromStart,chromEnd,name,score,strand,signalValue,pValue,qValue,peak
0,chr6,33789021,33789449,.,1000,.,483.48822,-1.0,4.62705,217
1,chr20,10434942,10435377,.,1000,.,482.86921,-1.0,4.62705,233
2,chr19,49817916,49818380,.,1000,.,474.64664,-1.0,4.62705,220
3,chr1,110034384,110034814,.,1000,.,473.88893,-1.0,4.62705,163
4,chr16,87392080,87392393,.,1000,.,473.05367,-1.0,4.62705,151
...,...,...,...,...,...,...,...,...,...,...
20791,chr10,114096482,114096798,.,610,.,4.94941,-1.0,0.15952,158
20792,chr1,23168119,23168435,.,562,.,4.94706,-1.0,0.15941,158
20793,chr19,19643547,19643863,.,775,.,4.93649,-1.0,0.15790,158
20794,chr20,33663756,33664072,.,584,.,4.92921,-1.0,0.15810,158
20795,chr1,226407239,226407555,.,687,.,4.92817,-1.0,0.15803,158

In [11]:
bed_Np_orig.isnull().values.any()

False

In [12]:
bed_Np_orig.isnull().sum().sum()

0

In [26]:
bed_Np_qVal_sorted = bed_Np_orig.sort_values(['qValue','signalValue','score'], ascending = False)

In [27]:
bed_Np_qVal_sorted

,chrom,chromStart,chromEnd,name,score,strand,signalValue,pValue,qValue,peak
0,chr6,33789021,33789449,.,1000,.,483.48822,-1.0,4.62705,217
1,chr20,10434942,10435377,.,1000,.,482.86921,-1.0,4.62705,233
2,chr19,49817916,49818380,.,1000,.,474.64664,-1.0,4.62705,220
3,chr1,110034384,110034814,.,1000,.,473.88893,-1.0,4.62705,163
4,chr16,87392080,87392393,.,1000,.,473.05367,-1.0,4.62705,151
...,...,...,...,...,...,...,...,...,...,...
20791,chr10,114096482,114096798,.,610,.,4.94941,-1.0,0.15952,158
20792,chr1,23168119,23168435,.,562,.,4.94706,-1.0,0.15941,158
20794,chr20,33663756,33664072,.,584,.,4.92921,-1.0,0.15810,158
20795,chr1,226407239,226407555,.,687,.,4.92817,-1.0,0.15803,158
20793,chr19,19643547,19643863,.,775,.,4.93649,-1.0,0.15790,158

In [28]:
bed_Np_qVal_sorted_top1000 = bed_Np_qVal_sorted.head(1000)

In [29]:
bed_Np_qVal_sorted_top1000

,chrom,chromStart,chromEnd,name,score,strand,signalValue,pValue,qValue,peak
0,chr6,33789021,33789449,.,1000,.,483.48822,-1.0,4.62705,217
1,chr20,10434942,10435377,.,1000,.,482.86921,-1.0,4.62705,233
2,chr19,49817916,49818380,.,1000,.,474.64664,-1.0,4.62705,220
3,chr1,110034384,110034814,.,1000,.,473.88893,-1.0,4.62705,163
4,chr16,87392080,87392393,.,1000,.,473.05367,-1.0,4.62705,151
...,...,...,...,...,...,...,...,...,...,...
995,chr19,37779469,37779720,.,1000,.,241.56200,-1.0,4.62705,129
996,chr5,160119233,160119510,.,1000,.,241.56193,-1.0,4.62705,144
997,chr12,113185303,113185565,.,1000,.,241.14477,-1.0,4.62705,122
998,chr20,45881132,45881385,.,1000,.,241.03950,-1.0,4.62705,120
999,chr6,31664869,31665115,.,1000,.,240.95224,-1.0,4.62705,144

In [31]:
bed_Np_qVal_sorted_top1000.to_csv('/home/ignat/Downloads/chip_seq_test/top_1000_peaks.bed',sep = '\t',index = False)